[Prefix="Grapheme::"]
interface Real {
    void Real(long precision);
    void set_precision(long precision);
    long get_precision();
    void set_value_from_float(double value);
    void set_value_from_string(DOMString value);
    DOMString get_value(long precision);
    DOMString get_value_no_point(long precision);
    void set_value_from_real([Ref] Real r);
    void set_nan();
    void set_inf(long sign);
    void set_zero(long sign);
    double approximate_as_float();
    void add_float(double value);
    void add_real([Ref] Real r);
    void subtract_float(double value);
    void subtract_real([Ref] Real r);
    void multiply_float(double value);
    void multiply_real([Ref] Real r);
    void square();
    void divide_float(double value);
    void divide_real([Ref] Real r);
    void pow_real([Ref] Real r);
    void pow_rational(long p, long q);
    void pow_int(long p);
    void sqrt();
    void cbrt();
    void rootn(long n);
    void ln();
    void log10();
    void log2();
    void exp();
    void exp2();
    void exp10();
    void sin();
    void cos();
    void tan();
    void sec();
    void csc();
    void cot();
    void acos();
    void asin();
    void atan();
    void sinh();
    void cosh();
    void tanh();
    void sech();
    void csch();
    void coth();
    void acosh();
    void asinh();
    void atanh();
    void asech();
    void acsch();
    void acoth();
    void gamma();
    void factorial();
    void ln_gamma();
    void digamma();
    void set_pi();
    long is_nan();
    long is_inf();
};
